trigger:
  - bicepazdo

variables:
  TestSubscriptionId: "89f21b48-2a5e-477c-ac88-c9cbb8401024"
  TestServiceConnectionName: "scAzureSponsorshipForBicep"

  ProdSubscriptionId: "54a2dff3-7c83-413e-9911-9f21a039e595"
  ProdServiceConnectionName: "scVSSubscriptionForBicep"
  #usWebAppId: "1webAppId"
  #weWebAppId: "2webAppId"
  #asiWebAppId: "3webAppId"  

stages:
  - stage: build
    displayName: Publish Bicep Files
    jobs:
      - job: publishbicep
        displayName: Publish bicep files as pipeline artifacts
        steps:
          - template: ./templates/transpile-job.yml

  - stage: deployinfratest
    dependsOn: build
    displayName: Deploy to test

    variables:
      environmentName: "test"


    jobs:
      - job: deploy_us_test              
        displayName: Deploy infra to US region test
        steps:
          - template: ./templates/deploy-arm.yml
            name: deployus
            parameters:
              seriviceConnectionName: ${{ variables.TestServiceConnectionName }}
              subscriptionId: ${{ variables.TestSubscriptionId }}
              location: "westus"
              locationAbbriviation: "us"
              environmentName: ${{ variables.environmentName }}
          - bash: |
              echo "##vso[task.setvariable variable=usWebAppId;]$(webAppId)"              
          - task: Bash@3
            displayName: Output in the same job 1
            inputs:
              targetType: inline
              script: |
                echo "el Id es = $(usWebAppId)"                

      - job: deploy_eur_test
        displayName: Deploy infra to EUR region test
        dependsOn: deploy_us_test
        steps:
          - template: ./templates/deploy-arm.yml
            name: deployeur
            parameters:
              seriviceConnectionName: ${{ variables.TestServiceConnectionName }}
              subscriptionId: ${{ variables.TestSubscriptionId }}
              location: "westeurope"
              locationAbbriviation: "we"
              environmentName: ${{ variables.environmentName }}
          - bash: |
              echo "##vso[task.setvariable variable=weWebAppId;]$(webAppId)"  
          - task: Bash@3
            displayName: Output in the same job 2
            inputs:
              targetType: inline
              script: |
                echo "el Id es = $(weWebAppId)"                

      - job: deploy_asia_test
        displayName: Deploy infra to ASIA region test
        dependsOn: deploy_eur_test
        steps:
          - template: ./templates/deploy-arm.yml
            name: deployasia
            parameters:
              seriviceConnectionName: ${{ variables.TestServiceConnectionName }}
              subscriptionId: ${{ variables.TestSubscriptionId }}
              location: "eastasia"
              locationAbbriviation: "asi"
              environmentName: ${{ variables.environmentName }}
          - bash: |
              echo "##vso[task.setvariable variable=asiWebAppId;]$(webAppId)"       
          - task: Bash@3
            displayName: Output in the same job 3
            inputs:
              targetType: inline
              script: |
                echo "el Id es = $(asiWebAppId)"                         

      - job: deploy_trafficmgr_test
        displayName: Deploy traffic manager test
        dependsOn: deploy_asia_test
        steps:
          - task: Bash@3
            displayName: Output in another job
            inputs:
              targetType: inline
              script: |
                echo "el Asi Id es = $(deploy_asia_test.deployasia.asiWebAppId)"         
          - template: ./templates/traffic-manager.yml
            parameters:
              seriviceConnectionName: ${{ variables.TestServiceConnectionName }}
              subscriptionId: ${{ variables.TestSubscriptionId }}
              location: "westeurope"
              environmentName: ${{ variables.environmentName }}
              usWebAppId: ${{ variables.usWebAppId }}
              weWebAppId: ${{ variables.weWebAppId }}
              asiWebAppId: ${{ deployasia.asiWebAppId }}

