trigger:
  - bicepazdo

stages:
  - stage: build
    displayName: Publish Bicep Files
    jobs:
      - job: publishbicep
        displayName: Publish bicep files as pipeline artifacts
        steps:
          - bash: ls
            displayName: "Lista componentes"
          - template: ./templates/transpile-job.yml

  - stage: deployinfratest
    dependsOn: build
    displayName: Deploy to test
    jobs:
      - job: deploy_us_test
        displayName: Deploy infra to US region test
        steps:
          - template: ./templates/deploy-arm.yml
            parameters:
              seriviceConnectionName: "scAzureSponsorshipForBicep"
              subscriptionId: "89f21b48-2a5e-477c-ac88-c9cbb8401024"
              environmentName: "test"
              location: "westus"
              locationAbbriviation: "us"